### ISSUE TITLE
CW1

### ISSUE THREAD

**Issue by oleksandrblazhko** [oleksandrblazhko/ai202-nezhivih#12]
https://drive.google.com/file/d/1Jupr5VQFJpOmHJSJY9Vu2JgmrSXgxk2I/view

**Comment by Nezhyvykh** [comment]
Завдання 1
Проживання вдома
Для споживача не складно знайти житло, тому воно доступне
Для споживача присутні зрозумілі пояснення як правильно складати договір, тому усе зрозуміло
Для споживача є актуальною інформація про оренду житла яка відповідає змісту на Веб-сторінках агенцій, тому усе актуально
Завдання 2
Мета пп: Знайти житло у живописному місці та отримати дані про вологість навколишнього середовищав обраному регіоні
Перший прецендент Авторизувати користувача наближає користувача пп до досягнення мети тим, що він допомогає користувачу отримати доступ до можливостей програмного продукту, а саме отримати дані про вологість у обраному регіоні, переглянути список доступного житла та ознайомимтись з рекомендаціями щодо живописних місць поблизу
Другий прецендент Знайти житло у живописному місці допогає знайти нове житло користувачу
Третій прецендент Сплатити житло допомагає саме отримати нове житло у убраному регіону

**Comment by oleksandrblazhko** [comment]
Оцінка = 3 бали
